### ISSUE TITLE
Character sheet notes emptied when adding ability

### ISSUE THREAD

**Issue by fredhicks** [megastruktur/foundryvtt-blades-in-the-dark#48] opened 2020-05-17 14:19 UTC
When adding a new ability (possibly other items) to a given actor's character sheet, the notes in the notes tab of their sheet get blanked out.

**Comment by megastruktur** [comment] 2020-05-18 13:56
Tested today on a fresh 0.5.7 installation and can not reproduce the issue, everything seems to be fine.
First I've added "Notes", then dropped several Abilities, Items, removed and added back Heritage. Seems like I don't have any issue.

@fredhicks Can you please check one more time?  :)  Also make sure you don't have any errors in Browser Console (press "F12"). If you have any - post them here please  :)

**Comment by fredhicks** [comment] 2020-05-19 15:38
After updating the module, I'm still having the problem happen, and there aren't any errors showing up. I did notice one interesting thing — if the note I put in the note field is pretty short, e.g., "Test", then it seems to persist just fine through me adding and removing items from a character's loadout (as one example). But when I go in there and expand it to "Test test test test test test test test test" and then add or drop a loadout item, the notes field resets to "Test". So I think something's up with the length/size of the notes data, in a non-error-throwing bug sort of way.

Here's a dropbox folder with a sequence of screenshots that show the issue happening. In the first half you see the notes field with "Test" in it persisting just fine when I drop an item from the loadout. In the second half I expand the notes content to "Test test test test test" (etc) and then go and drop another item from the loadout. When I go back to the notes after doing that, the notes content has reset to "Test" rather than keeping the newer, longer content.

No error messages come up in the console at all during all of this:

Foundry VTT | Deleted OwnedItem 8GNvNLCCcAxZFLx4 from parent Actor UloYn6Krswf1m5hL
foundry.js:10192 Foundry VTT | Deleted OwnedItem IQ0gIaiLoAUDtSv0 from parent Actor UloYn6Krswf1m5hL
2foundry.js:3745 Foundry VTT | Rendering Dialog

**Comment by megastruktur** [comment] 2020-05-20 09:53
@fredhicks Yep, you got it right, I was able to replicate the issue. Now working on the fix.

**Comment by megastruktur** [comment] 2020-05-20 09:59
The problem description: field is not saved when "Add Item" popup re-renders the Actor entity.

**Comment by megastruktur** [comment] 2020-05-20 10:05
Whoops seems like a FoundryVTT issue (I was able to reproduce the same behavior with simpleworldbuilding system). I will contact Foundr staff.

@fredhicks for the time being you can save the value by closing the character sheet. This will work  :)

**Closed** 2020-05-20 11:55 UTC

**Comment by megastruktur** [comment] 2020-05-20 21:33
@fredhicks I made a fix, you can try it (0.5.2)
Next Foundry update should fix this issue globally.
